import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import Hero from "../components/Hero";
import FirstPage from "../components/FirstPage";
import Slider from "../components/Slider";
import { SliderData } from "../components/SliderData";
import Instagram from "../components/Instagram";
import SecondPage from "../components/SecondPage";
import ThirdPage from "../components/ThirdPage";
import FourthPage from "../components/FourthPage";
import FifthPage from "../components/FifthPage";
import SixthPage from "../components/SixthPage";
import SeventhPage from "../components/SeventhPage";
import EightPage from "../components/EightPage";
import NinthPage from "../components/NinthPage";
import Contato from "../components/Contato";

export default function Home() {
  return (
    <div>
      <Head>
        <title>RubBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <FirstPage />
      <SecondPage />
      <ThirdPage />
      <FourthPage />
      <FifthPage />
      <SixthPage />
      <SeventhPage />
      <EightPage />
      <NinthPage />
      <Contato />
    </div>
  );
}
