import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import {SliderData} from '../components/SliderData'
import Instagram from '../components/Instagram'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RubBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Hero  heading='RubBank App' message='Eficiência, robustez e praticidade'/>
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
